# Generated by Django 4.0.5 on 2022-07-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_images_alter_post_options_post_accurate_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="photo_ref",
        ),
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.ImageField(
                blank=True,
                db_index=True,
                null=True,
                upload_to="photos\\%Y\\%m\\%d",
                verbose_name="Фото",
            ),
        ),
    ]
