# Generated by Django 4.0.5 on 2022-08-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_images_options_alter_images_post_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="group_id",
        ),
    ]
