# Generated by Django 4.0.5 on 2022-08-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_remove_group_group_id_add_group_is_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="is_hidden",
            field=models.BooleanField(default=False, verbose_name="Скрытая группа"),
        ),
    ]
