# Generated by Django 4.0.5 on 2022-08-16 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_group_is_hidden"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="images",
            name="post_id",
        ),
        migrations.AddField(
            model_name="images",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.post",
                verbose_name="ID поста",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.group",
                verbose_name="ID автора поста",
            ),
        ),
    ]
