# Generated by Django 4.0.5 on 2022-08-31 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_images_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='photos',
        ),
    ]
