# Generated by Django 4.0.5 on 2022-08-31 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_rename_images_post_photos"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="images",
            options={
                "ordering": ["post_id"],
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
        migrations.AddField(
            model_name="images",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.post",
                verbose_name="ID поста",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="photos",
            field=models.ManyToManyField(
                blank=True, related_name="post_photos", to="main.images"
            ),
        ),
    ]
